name=input("Enter your name")
branch=input("What is your Branch?")
g=input("Gender?")
clg=input("Write your college name..")
age=int(input("What is your age?"))
print("Name:",name)
print("Branch:",branch)
print("Gender:",g)
print("College Name:",clg)
print("Age:",age)
